# Conversion performed at 2026-07-09 13:39:07.708980
dovecot_config_version = 2.4.1
dovecot_storage_version = 2.4.0

protocols {
  imap = yes
  sieve = yes
  pop3 = yes
}
# is more or less this:
# !include_try /usr/share/dovecot/protocols.d/*.protocol

# Including override files (they must be included before any filter
# that make use of global setting
!include_try {DOVECOT_CONF_DIR}/imscp.d/*.conf

auth_allow_cleartext = yes
auth_mechanisms = plain login

default_client_limit = {DOVECOT_DEFAULT_CLIENT_LIMIT}
listen = {NETWORK_PROTOCOLS}

mail_driver = maildir
mail_max_userip_connections = {DOVECOT_MAX_USERIP_CONNECTIONS}

mail_path = ~/
mail_plugins = quota

namespace inbox {
  inbox = yes
  prefix = INBOX.
  type = private

  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }

  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }

  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }

  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
}

!include_try {DOVECOT_CONF_DIR}/dovecot-sql.conf

#passdb sql {
#  driver = sql
#}

userdb prefetch {
  driver = prefetch
}

#userdb sql {
#  driver = sql
#}

quota User {
  driver = maildir
}

# Trash Quota +100M...
#namespace {
#  mailbox INBOX.Trash {
#  }
#}

quota_warning warning-1 {
  quota_storage_percentage = 95

  execute quota-warning {
    args = 95 %{user}
  }
}

quota_warning warning-2 {
  quota_storage_percentage = 80

  execute quota-warning {
    args = 80 %{user}
  }
}

service auth {
  unix_listener auth-master {
    mode = 0600
    user = {MTA_MAILBOX_UID_NAME}
  }
  unix_listener {DOVECOT_SASL_AUTH_SOCKET_PATH} {
    group = {POSTFIX_GROUP}
    mode = 0660
    user = {POSTFIX_USER}
  }
}

service imap-login {
  process_limit = {DOVECOT_IMAP_LOGIN_PROCESS_LIMIT}
  process_min_avail = {DOVECOT_IMAP_LOGIN_PROCESS_MIN_AVAIL}
  restart_request_count = {DOVECOT_IMAP_LOGIN_PROCESS_SERVICE_COUNT}
}

service imap {
  process_limit = {DOVECOT_IMAP_PROCESS_LIMIT}
  process_min_avail = {DOVECOT_IMAP_PROCESS_MIN_AVAIL}
  restart_request_count = {DOVECOT_IMAP_PROCESS_SERVICE_COUNT}
  vsz_limit = {DOVECOT_IMAP_VSZ_LIMIT}
}

service pop3-login {
  process_limit = {DOVECOT_POP3_LOGIN_PROCESS_LIMIT}
  process_min_avail = {DOVECOT_POP3_LOGIN_PROCESS_MIN_AVAIL}
  restart_request_count = {DOVECOT_POP3_LOGIN_PROCESS_SERVICE_COUNT}
}

service pop3 {
  process_limit = {DOVECOT_POP3_PROCESS_LIMIT}
  process_min_avail = {DOVECOT_POP3_PROCESS_MIN_AVAIL}
  restart_request_count = {DOVECOT_POP3_PROCESS_SERVICE_COUNT}
}

service quota-warning {
  executable = script {ENGINE_ROOT_DIR}/quota/imscp-dovecot-quota.sh
  group = {IMSCP_GROUP}

  unix_listener quota-warning {
    mode = 0600
    user = {MTA_MAILBOX_UID_NAME}
  }
}

protocol imap {
  imap_logout_format = in=%{input} out=%{output}

  mail_plugins {
    imap_quota = yes
  }
}

protocol pop3 {
  pop3_logout_format = top=%{top_count}/%{top_bytes}, retr=%{retr_count}/%{retr_bytes}, del=%{deleted_count}/%{message_count}, size=%{message_bytes}, in=%{input}, out=%{output}
  pop3_uidl_format = %{uid}-%{uidvalidity}
}

protocol lda {
  auth_socket_path = {DOVECOT_LDA_AUTH_SOCKET_PATH}
  postmaster_address = postmaster@{HOSTNAME}
}

# Warnings during conversion:
# - <memory>:47: maildir++ quota limits are no longer read
# - <memory>:48: manual conversion needed for quota rule
# - <memory>:49: manual conversion needed for quota rule
# - <memory>:170: mail_plugins uses $SET:mail_plugins but adds nothing
